import { createHash } from 'node:crypto'

export const iconSizes = [16, 24, 32, 48, 64, 128, 256, 512, 1024] as const
export const icoSizes = iconSizes.filter(size => size <= 256)
export const icnsTypes = new Map([[16, 'icp4'], [32, 'icp5'], [64, 'icp6'], [128, 'ic07'], [256, 'ic08'], [512, 'ic09'], [1024, 'ic10']])
export const sha256 = (data: string | Uint8Array): string => createHash('sha256').update(data).digest('hex')

export function masterGeometry(svg: string): { viewBox: string; paths: string[] } {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
  const paths = [...svg.matchAll(/<path id="(?:left|right|bottom)-page" d="([^"]+)"\s*\/>/g)].map(match => match[1]!)
  if (!viewBox || paths.length !== 3 || (svg.match(/<path\b/g)?.length ?? 0) !== 3 || /<(?:script|image|use|circle|rect)\b/.test(svg)) throw new Error('The master must contain exactly three editable page paths.')
  return { viewBox, paths }
}

export function geometryModule(svg: string): string {
  const { viewBox, paths } = masterGeometry(svg)
  return `// Generated by npm run branding:export from assets/branding/sculpted-aperture.svg.\n// Edit the SVG master, then regenerate; do not edit these paths independently.\nexport const brandViewBox = ${JSON.stringify(viewBox)}\nexport const brandPaths = ${JSON.stringify(paths, null, 2)} as const\n`
}

export function tileSvg(svg: string): string {
  const { paths } = masterGeometry(svg)
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">\n  <defs><linearGradient id="tile" x1="0" y1="0" x2="0.7" y2="1"><stop stop-color="#343940"/><stop offset="1" stop-color="#202329"/></linearGradient></defs>\n  <rect x="80" y="80" width="864" height="864" rx="182" fill="url(#tile)" stroke="#555A63" stroke-width="2"/>\n  <g fill="#CEAEF3" transform="translate(-81.75 -88) scale(.95)">\n${paths.map(path => `    <path d="${path}"/>`).join('\n')}\n  </g>\n</svg>\n`
}

export function makeIco(pngs: ReadonlyMap<number, Buffer>): Buffer {
  const header = Buffer.alloc(6 + icoSizes.length * 16)
  header.writeUInt16LE(1, 2); header.writeUInt16LE(icoSizes.length, 4)
  let offset = header.length
  const frames = icoSizes.map((size, index) => {
    const frame = pngs.get(size)!
    const entry = 6 + index * 16
    header[entry] = size === 256 ? 0 : size; header[entry + 1] = header[entry]!
    header.writeUInt16LE(1, entry + 4); header.writeUInt16LE(32, entry + 6)
    header.writeUInt32LE(frame.length, entry + 8); header.writeUInt32LE(offset, entry + 12)
    offset += frame.length
    return frame
  })
  return Buffer.concat([header, ...frames])
}

export function makeIcns(pngs: ReadonlyMap<number, Buffer>): Buffer {
  const chunks = [...icnsTypes].map(([size, type]) => {
    const png = pngs.get(size)!, header = Buffer.alloc(8)
    header.write(type, 0, 'ascii'); header.writeUInt32BE(png.length + 8, 4)
    return Buffer.concat([header, png])
  })
  const header = Buffer.alloc(8)
  header.write('icns', 0, 'ascii'); header.writeUInt32BE(8 + chunks.reduce((sum, chunk) => sum + chunk.length, 0), 4)
  return Buffer.concat([header, ...chunks])
}
