export interface FlowDefinition {
  title: string
  testFile: string
  screenshots: Record<string, string>
}

// Stable flow and checkpoint IDs are shared by tests, publication and discovery checks.
export const flows: Record<string, FlowDefinition> = {
  'account-connection': { title: 'Account connection and restoration', testFile: 'account.spec.ts', screenshots: {
    'account-protocol-fixture': 'Connected account panel using the signed local provider fixture.'
  } },
  'manual-sign-in': { title: 'Manual sign-in link', testFile: 'account.spec.ts', screenshots: {
    'manual-sign-in-link': 'Browser-opening recovery after copying the fixture sign-in link.'
  } },
  appearance: { title: 'Appearance and local preference', testFile: 'appearance.spec.ts', screenshots: {
    'settings-light': 'Light selected in the Appearance dialog.',
    'workspace-light': 'Light project composer with its existing learning draft.',
    'settings-dark': 'Dark selected through radio keyboard navigation.',
    'workspace-dark': 'Dark project composer with the same draft.',
    'account-dark': 'Disconnected account panel in Dark mode.'
  } },
  projects: { title: 'Project lifecycle and navigation', testFile: 'projects.spec.ts', screenshots: {
    'dashboard-empty': 'Empty dashboard before choosing a project folder.',
    'project-workspace': 'Project-specific goal draft and saved model preference.',
    'project-narrow': '600-pixel content width after dismissing the navigation drawer.',
    'project-zoom-200': 'Narrow project composer at 200% Electron zoom.'
  } },
  outline: { title: 'Outline generation and cancellation', testFile: 'outline.spec.ts', screenshots: {
    'outline-overview': 'Validated and saved outline generated by the local provider fixture.',
    'generated-outline': 'Expanded first topic with its module plan.'
  } },
  'outline-edit': { title: 'Whole-path outline rewriting', testFile: 'outline-edit.spec.ts', screenshots: {
    'outline-edit-light': 'Whole-path editor with a numbered change request in Light mode.',
    'outline-edit-dark': 'Preserved whole-path draft in Dark mode.',
    'outline-edit-zoom': 'Rewrite action remains reachable at 200% zoom.'
  } },
  'topic-edit': { title: 'Scoped topic rewriting', testFile: 'topic-edit.spec.ts', screenshots: {
    'topic-edit-light': 'Topic editor with its own change draft in Light mode.',
    'topic-edit-dark': 'The retained topic draft after cancellation, in Dark mode.',
    'topic-edit-zoom': 'Topic rewrite action remains reachable at 200% zoom.'
  } },
  materials: { title: 'Folder material and clarification', testFile: 'materials.spec.ts', screenshots: {
    'material-setup': 'Folder-only setup with an optional learning goal.',
    'material-coverage': 'Saved outline with supported and unsupported source coverage disclosed.',
    'unsupported-material': 'Recovery for a folder containing only unsupported learning files.'
  } },
  recovery: { title: 'Generation and save recovery', testFile: 'recovery.spec.ts', screenshots: {
    'generation-pending': 'A real utility-process request held by the local provider fixture.',
    'generated-unsaved': 'A generated outline retained after an actual filesystem save failure.',
    'usage-recovery': 'Provider usage-limit feedback with the learner draft preserved.'
  } },
  reading: { title: 'Long outlines and unavailable state', testFile: 'reading.spec.ts', screenshots: {
    'long-outline-zoom': 'Long offline outline at narrow width and 200% Electron zoom.',
    'unreadable-project': 'Corrupt project recovery without replacing its metadata.'
  } },
  'model-access': { title: 'Independent model access checks', testFile: 'model-test.spec.ts', screenshots: {
    'model-test-failed': 'Fixture rejection of a model test without removing the extra choices.',
    'model-test-verified-light': 'Independent successful Sol and Luna checks in Light mode.',
    'model-test-verified-dark': 'The same fixture verification state rendered in Dark mode.'
  } },
  diagnostics: { title: 'Development diagnostic boundaries', testFile: 'logging.spec.ts', screenshots: {} },
  'inference-diagnostics': { title: 'Inference diagnostic correlation', testFile: 'logging.spec.ts', screenshots: {} },
  'packaged-worker': { title: 'Packaged Pi worker', testFile: 'packaged-worker.spec.ts', screenshots: {} }
}

export function flowDefinition(id: string): FlowDefinition {
  if (!/^[a-z][a-z0-9-]*$/.test(id) || !Object.hasOwn(flows, id)) throw new Error(`Unknown flow: ${id}`)
  return flows[id]!
}

export function flowId(annotations: { type: string; description?: string }[]): string {
  const values = annotations.filter(item => item.type === 'flow')
  if (values.length !== 1 || !values[0]?.description) throw new Error('Each desktop test must declare exactly one flow annotation')
  flowDefinition(values[0].description)
  return values[0].description
}
