export interface FlowDefinition {
  title: string
  testFile: string
  screenshots: Record<string, string>
}

// Stable flow and checkpoint IDs are shared by tests, publication and discovery checks.
export const flows: Record<string, FlowDefinition> = {
  'account-connection': { title: 'Account connection and restoration', testFile: 'account.spec.ts', screenshots: {
    'account-protocol-fixture': 'Connected account panel using the signed local provider fixture.'
  } },
  'manual-sign-in': { title: 'Manual sign-in link', testFile: 'account.spec.ts', screenshots: {
    'manual-sign-in-link': 'Browser-opening recovery after copying the fixture sign-in link.'
  } },
  appearance: { title: 'Appearance and local preference', testFile: 'appearance.spec.ts', screenshots: {
    'settings-light': 'Light selected in the Appearance dialog.',
    'workspace-light': 'Light project composer with its existing learning draft.',
    'settings-dark': 'Dark selected through radio keyboard navigation.',
    'settings-zoom-dark': 'Dark Appearance controls in the sectioned Settings dialog at 600 pixels and 200% zoom with reduced motion.',
    'settings-zoom-light': 'The same reflowed Appearance controls in Light.',
    'workspace-dark': 'Dark project composer with the same draft.',
    'account-dark': 'Disconnected account panel in Dark mode.'
  } },
  'openrouter-settings': { title: 'Sectioned provider settings and request history', testFile: 'openrouter-settings.spec.ts', screenshots: {
    'settings-unavailable-light': 'The saved Seedream choice remains visible with its catalog absence reason in Light.',
    'settings-usage-light': 'Exact app spend, unresolved cost count and separately labelled key-wide usage in Light.',
    'settings-history-light': 'Filtered chapter-image history and unknown billing independent of save failure.',
    'settings-stale-dark': 'Dark connection recovery retains last-known pricing after failed metadata refresh.',
    'settings-narrow-dark': 'OpenRouter connection controls reflow at 600 pixels and 200% zoom in Dark with reduced motion.',
    'settings-narrow-light': 'The same reflowed connection controls in Light.'
  } },
  'openrouter-settings-admission': { title: 'Provider settings during owned inference', testFile: 'openrouter-settings.spec.ts', screenshots: {} },
  navigation: { title: 'Shared application navigation', testFile: 'navigation.spec.ts', screenshots: {
    'reading-restored-light': 'Restored Light reading context after traversing real project history.',
    'reading-current-dark': 'Current Dark outline after removing a remembered stable topic.',
    'compact-light': 'Reachable title-strip controls at 600 by 480 and 200% zoom in Light.',
    'compact-dark': 'Reachable title-strip controls at 600 by 480 and 200% zoom in Dark.'
  } },
  projects: { title: 'Project lifecycle and navigation', testFile: 'projects.spec.ts', screenshots: {
    'dashboard-empty': 'Empty dashboard before choosing a project folder.',
    'dashboard-empty-dark': 'The same empty dashboard in Dark.',
    'dashboard-populated-light': 'Both saved recent project rows in Light after restart.',
    'dashboard-populated-dark': 'The same populated dashboard in Dark, with project details preserved.',
    'missing-folder-light': 'Missing-folder recovery with its explicit Locate folder command in Light.',
    'missing-folder-dark': 'The same missing-folder recovery in Dark.',
    'project-workspace': 'Project-specific goal draft and saved model preference.',
    'project-narrow': '600-pixel content width after dismissing the navigation drawer.',
    'project-zoom-200': 'Narrow project composer at 200% Electron zoom.'
  } },
  outline: { title: 'Outline generation and cancellation', testFile: 'outline.spec.ts', screenshots: {
    'outline-streaming-light': 'Selectable partial structured draft in the Light workbench dock before clean EOF.',
    'outline-streaming-dark': 'Dark streaming dock after growth with manual preview position preserved.',
    'outline-streaming-zoom': 'Streaming dock and reachable Cancel at minimum window size and 200% Electron zoom.',
    'outline-overview': 'Validated and saved outline generated by the local provider fixture.',
    'generated-outline': 'Expanded first topic with its module plan.'
  } },
  'outline-edit': { title: 'Whole-path outline rewriting', testFile: 'outline-edit.spec.ts', screenshots: {
    'saved-topic-receiving-zoom': 'Saved-topic reading action remains usable with the real receiving dock at minimum size and 200% zoom.',
    'saved-topic-saving-zoom': 'Saved-topic reading action remains usable while validated publication is held at 600 by 480 and 200% zoom.',
    'outline-edit-rejected': 'Raced admission rejection preserves the editor and its input while the diagnostic owns AI activity.',
    'outline-edit-light': 'Whole-path editor with a numbered change request in Light mode.',
    'outline-edit-dark': 'Preserved whole-path draft in Dark mode.',
    'outline-edit-zoom': 'Rewrite action remains reachable at 200% zoom.'
  } },
  'topic-edit': { title: 'Scoped topic rewriting', testFile: 'topic-edit.spec.ts', screenshots: {
    'topic-streaming-light': 'Selected-topic-only provisional draft with a trusted saved topic title and connected actual activities.',
    'topic-streaming-zoom': 'Long topic request and reachable independent draft/activity regions at narrow width and 200% zoom.',
    'topic-edit-light': 'Topic editor with its own change draft in Light mode.',
    'topic-edit-dark': 'The retained topic draft after cancellation, in Dark mode.',
    'topic-edit-zoom': 'Topic rewrite action remains reachable at 200% zoom.'
  } },
  materials: { title: 'Folder material and clarification', testFile: 'materials.spec.ts', screenshots: {
    'material-setup': 'Folder-only setup with an optional learning goal.',
    'material-setup-dark': 'The same material-led setup in Dark.',
    'material-clarification-light': 'Editable clarification request and its retained answer in Light.',
    'material-clarification-dark': 'The same clarification state in Dark.',
    'material-coverage': 'Saved outline with supported and unsupported source coverage disclosed.',
    'unsupported-material': 'Recovery for a folder containing only unsupported learning files.',
    'unsupported-material-dark': 'The same unsupported-source recovery in Dark.'
  } },
  recovery: { title: 'Generation and save recovery', testFile: 'recovery.spec.ts', screenshots: {
    'generation-pending': 'A real utility-process request held by the local provider fixture.',
    'generated-unsaved': 'A generated outline retained after an actual filesystem save failure.',
    'generated-unsaved-dark': 'The same retained unsaved outline and storage-only retry in Dark.',
    'usage-recovery': 'Provider usage-limit feedback with the learner draft preserved.',
    'usage-recovery-dark': 'The same usage-limit recovery in Dark.'
  } },
  'topic-reading': { title: 'Saved topic reading and history', testFile: 'topic-reading.spec.ts', screenshots: {
    'saved-overview-light': 'Saved overview with full context and independent quiet commands in Light.',
    'saved-overview-dark': 'Saved overview with independent quiet commands in Dark.',
    'saved-topic-light': 'Complete saved topic with its retained learning-task disclosure in Light.',
    'saved-topic-dark': 'Current renamed saved topic in Dark without inference.',
    'saved-topic-readonly': 'Typed main-sent read-only presentation fixture retains saved reading and its issue while edits are disabled.',
    'saved-topic-readonly-dark': 'The same typed read-only saved-topic presentation in Dark.',
    'saved-topic-zoom': 'Independent topic actions at 600 pixels and 200% Electron zoom.',
    'missing-topic-overview': 'A removed saved topic resolves to its current owning outline with an explanation.',
    'missing-topic-overview-light': 'The same removed-topic fallback and reason in Light.'
  } },
  reading: { title: 'Long outlines and unavailable state', testFile: 'reading.spec.ts', screenshots: {
    'long-outline-zoom': 'Long offline outline at narrow width and 200% Electron zoom.',
    'unreadable-project': 'Corrupt project recovery without replacing its metadata.',
    'unreadable-project-dark': 'The same corrupt-metadata recovery in Dark.',
    'refinement-light': 'Saved-outline refinement with the retained learner draft in Light.',
    'refinement-dark': 'The same refinement form and retained draft in Dark.'
  } },
  'model-access': { title: 'Independent model access checks', testFile: 'model-test.spec.ts', screenshots: {
    'model-test-dashboard-waiting': 'Global diagnostic panel remains discoverable after navigation to the project-free dashboard.',
    'model-test-failed': 'Fixture rejection of a model test without removing the extra choices.',
    'model-test-waiting-hint': 'A real 30-second silent response remains cancellable with a nonterminal waiting explanation.',
    'model-test-verified-light': 'Independent successful Sol and Luna checks in Light mode.',
    'model-test-verified-dark': 'The same fixture verification state rendered in Dark mode.'
  } },
  diagnostics: { title: 'Development diagnostic boundaries', testFile: 'logging.spec.ts', screenshots: {} },
  'inference-diagnostics': { title: 'Inference diagnostic correlation', testFile: 'logging.spec.ts', screenshots: {} },
  'ai-streaming': { title: 'Real long stream and domain acceptance', testFile: 'ai-streaming.spec.ts', screenshots: {
    'stream-waiting': 'Real comment bytes keep the waiting operation alive before structured output.',
    'stream-structured-light': 'Fragmented structured arguments form a provisional Light draft after a bounded burst.',
    'stream-structured-dark': 'The same genuine provisional draft in Dark with reduced motion.',
    'stream-past-190': 'Active receiving draft and reachable Cancel after 190 real seconds; saved metadata is unchanged.',
    'stream-saving': 'Validated output waits at the real scoped file write; Cancel is unavailable during publication.',
    'stream-saved': 'The complete accepted outline is saved after more than 200 seconds of receiving.',
    'stream-checking': 'Real clean-EOF diagnostic evidence awaits delivery of its actual process exit before independent verification.'
  } },
  'ai-streaming-repair': { title: 'Structured candidate repair', testFile: 'ai-streaming.spec.ts', screenshots: {
    'repair-first-draft': 'A genuine first structured draft is provisional and has not entered saved project state.',
    'repair-replacement': 'The second provider turn replaces the rejected candidate rather than appending it.',
    'repair-saved': 'Only the independently valid replacement becomes the saved outline.'
  } },
  'packaged-worker': { title: 'Packaged Pi worker', testFile: 'packaged-worker.spec.ts', screenshots: {} },
  'image-worker': { title: 'Sanctioned image utility transport and accounting', testFile: 'image-worker.spec.ts', screenshots: {} },
  'topic-content': { title: 'Checkpointed illustrated chapter lifecycle', testFile: 'topic-content.spec.ts', screenshots: {} },
  'topic-content-preflight': { title: 'Explicit image metadata preflight', testFile: 'topic-content.spec.ts', screenshots: {} },
  'topic-content-recovery': { title: 'Explicit illustration completion and retry', testFile: 'topic-content.spec.ts', screenshots: {} },
  'topic-content-barriers': { title: 'Chapter durable-write and cleanup barriers', testFile: 'topic-content.spec.ts', screenshots: {} },
  'topic-media': { title: 'Authorized local chapter media', testFile: 'topic-content.spec.ts', screenshots: {} }
}

export function flowDefinition(id: string): FlowDefinition {
  if (!/^[a-z][a-z0-9-]*$/.test(id) || !Object.hasOwn(flows, id)) throw new Error(`Unknown flow: ${id}`)
  return flows[id]!
}

export function flowId(annotations: { type: string; description?: string }[]): string {
  const values = annotations.filter(item => item.type === 'flow')
  if (values.length !== 1 || !values[0]?.description) throw new Error('Each desktop test must declare exactly one flow annotation')
  flowDefinition(values[0].description)
  return values[0].description
}
